# Generated by Django 4.2.2 on 2023-12-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='location',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='marker',
            name='map_url',
            field=models.CharField(max_length=1000),
        ),
    ]
