# Generated by Django 4.2.2 on 2023-12-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_alter_marker_location_alter_marker_map_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='program',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='marker',
            name='scholarship',
            field=models.BooleanField(default=False),
        ),
    ]
