# Generated by Django 4.2.2 on 2023-12-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_marker_program_marker_scholarship'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='contact',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='marker',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='website',
            field=models.URLField(max_length=100),
        ),
    ]
