# Generated by Django 4.2.2 on 2023-12-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='program_type',
            field=models.CharField(choices=[('BA', 'Bachelor of Arts'), ('BS', 'Bachelor of Science'), ('BBA', 'Bachelor of Business Administration'), ('BEng', 'Bachelor of Engineering'), ('BFA', 'Bachelor of Fine Arts'), ('BEd', 'Bachelor of Education'), ('BSN', 'Bachelor of Nursing'), ('LLB', 'Bachelor of Law'), ('BCom', 'Bachelor of Commerce'), ('BSW', 'Bachelor of Social Work'), ('NA', 'Other')], default='NA', max_length=5),
        ),
    ]
