# Generated by Django 4.2.2 on 2023-12-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_marker_program_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/logos/'),
        ),
    ]
