# Generated by Django 4.2.2 on 2023-12-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_alter_marker_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
