# Generated by Django 4.2.2 on 2023-12-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0012_program_remove_marker_program_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
    ]
